# Stela Data Access
stela_data_access:
  outputs:
    dev:
      dataset: stela_data_sandbox
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "../creds/dbt-runner-sa-creds-dev.json"
      location: US
      method: service-account
      priority: interactive
      project: nyt-stelaplat-dev
      threads: 1
      type: bigquery
  target: dev
# /Stela Data Access
